### ISSUE TITLE
Version validation fail from unity 7.10.0-beta

### ISSUE THREAD

**Issue by vince137** [GameAnalytics/GA-SDK-UNITY#33] opened 2024-06-05 21:48 UTC
Hey,

Running with the last version from master, I have the following error during the init:

`Info/GameAnalytics: Validation fail - configure sdk version: Sdk version not supported. String: unity 7.10.0-beta`

Seems like the `-beta` is not handled by the validation regex.

**Comment by dorin-ga** [comment] 2024-06-06 07:05
Hello, on what platform is this happening?

**Comment by vince137** [comment] 2024-06-06 13:30
> Hello, on what platform is this happening?

WindowsPlayer

**Comment by dorin-ga** [comment] 2024-06-14 11:14
We have found the cause and will be rolling out a fix for this issue.

**Closed by dorin-ga** 2024-06-14 11:14 UTC
